### ISSUE TITLE
Add headless script to create Ghidra shared project

### ISSUE THREAD

**Issue by Enigmatrix** [Enigmatrix/pwnbro#4]
Supposedly only creatable through GUI or a script, not auto created by the command line headlessAnalyzer.

Need to use the [GhidraProject](https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/Base/src/main/java/ghidra/base/project/GhidraProject.java#L153) class in a headless script. It should take in an argument which is the name of the project.

Future work can be deletion of the project.

**Comment by daniellimws** [comment]
Added in 60ce511

Ready to close?
